### ISSUE TITLE
my proposals 

### ISSUE THREAD

**Issue by ApayRus** [osk/node-webvtt#43]
i have some thoughts about parser, can I share them with you? 

Here is my file:
```
WEBVTT - this is coolest format for subtitles ever!!
Thank you for download this subtitles. 
author: aparus
title: my movie title
language: en

NOTE 
Scene 1. Actors:
Fred: https://avatars.com/fred-avatar.png
John: https://avatars.com/john-avatar.png

00:00:00.500 --> 00:00:02.000
<v.loud Fred> The Web is always changing. 

00:00:04.500 --> 00:00:05.678
<v.silent John> Yes. And it is good. 

00:00:07.323 --> 00:00:08.437
<v.loud Fred>  and the way we access it is changing
```
1) first line comment is lost ever, may be we should store in meta? like firstLineComment etc? 
2) line without `:` in meta appears like properties:`{'Thank you for download this subtitles': 'Thank you for download this subtitles. '}`. Key is not predefined , but is variable.... may be better to use something like: `{plainText: 'Thank you for download this subtitles. '}`.  and join there all  text without keys? 
3) What about voice tag and its styles? Would you like to process them too? additional fields to cue: `{voice: 'Fred', style: 'loud'}`
4) Also store NOTEs? I want to put there some additional info, like scene info, avatars to actors etc. 

If you like some of them, I'll open pull request, when I realize them. But I need your opinion first. 

Thank you for your attention. Best regards.

**Comment by goatandsheep** [comment]
1. I'm not sure this is consistent with the [w3 webvtt standard format](https://www.w3.org/TR/webvtt1/#file-structure). If you can show an example somewhere we can figure something out
2. Description should really go after the WEBVTT word where you have "this is the coolest format for subtitles ever!!" or as a NOTE I think?
3. I like this idea, but I think let's think practically for a moment: what are some ways that the JSON output will need to be reformatted? There are quite a lot of tags including style tags, voice tags, karaoke-style time tags, etc. But I digress, one application I can think of that may benefit from the voice is if we want to convert to _other_ formats, such as TTML. However, in that case, you should take a look at [the documentation for TTML voices](https://www.w3.org/TR/ttml1/#metadata-vocabulary-actor). Or perhaps being able to easily switch between multiple voices in an interface?
4. This is a good idea. We previously decided to not include NOTE because we wanted to be consistent with the [VTTCue API](https://developer.mozilla.org/en-US/docs/Web/API/VTTCue). I'm not sure how it works with NOTE tbh. I guess it couldn't hurt!

These are great suggestions. What is an application for which you need the JSON to be easily modifiable?

**Comment by ApayRus** [comment]
@goatandsheep thank you  for answer! 
I have done a couple of parsers since this message ) 
I extract a tag <v.class1.class2 Ahmed> into an object: { voice: { name:"Ahmed", classes: ['class1', 'class2' ] } } 
and keep Note, then parse it with yaml-parser. 

I'm doing learning apps. And have a several goals. One of them is -- to display subtitles as a book -- with chapters menu navigation, and character avatars near they cues (like in chat). 

Also I do player for podcasts. 
![Screenshot from 2021-01-06 05-24-21](https://user-images.githubusercontent.com/1222611/103722174-73dc0600-4fe0-11eb-869b-6790fcc7dba5.png)

**Comment by goatandsheep** [comment]
@Aparus very cool! Do you have a public fork of this project that you're working in?

**Comment by ApayRus** [comment]
@goatandsheep , it's not fork. I did it from the scratch )) 
I'm sorry for lack of docs, you can see examples in test files. 
It's universal subtitles parser (for srt, vtt, audacity labeles) -- for my purposes. 
May be voice tag extractor will be useful for you. 
https://github.com/Aparus/frazy-parser

About parse vtt as a book with chapters  -- I can't find it. I was working on it a couple of days and now can't find any peace of code about it.  It makes me crazy )

**Comment by ApayRus** [comment]
@goatandsheep oh, it was in codesandbox, of course )) but it is messy one. 
https://codesandbox.io/s/vttjs-uyyvs?file=/src/myParser.js

**Comment by osk** [comment]
@ApayRus closing this, feel free to re-open or open new issues per feature suggestion
