### ISSUE TITLE
Webvtt parser breaking with X-TIMESTAMP-MAP

### ISSUE THREAD

**Issue by clipod** [osk/node-webvtt#72]
Content: 

```
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0

1
00:00.300 --> 00:01.889
This is from a recruit, and I've

2
00:01.890 --> 00:03.329
asked them if I can have one of the

3
00:03.330 --> 00:04.849
six consulting conversations, I

4
00:05.010 --> 00:06.509
said, can I do a tech assessment

5
00:06.510 --> 00:08.189
with you? And then they said, no,

6
00:08.340 --> 00:10.230
I do not need a tech assessment.
```

Error:
```
[Error: Missing blank line after signature] { error: undefined }
Waiting for the debugger to disconnect...

Error: Error: Missing blank line after signature
```

Not sure why X-TIMESTAMP-MAP is not supported.

**Comment by slifty** [comment]
Just wanted to chime in to note that I'm facing this issue as well; since this issue is pretty old with no response I'm going to likely fork and patch locally (happy to contribute a PR upstream as well)

This discussion may be relevant to the issue: https://github.com/w3c/webvtt/issues/485

Ultimately there is some confusion in the spec, but The Powers That Be have weighed in to suggest that this *should* be considered valid: https://mailarchive.ietf.org/arch/msg/hls-interest/4vmLpEsV-EnmkEwMQZkzbGQai_4/

Specifically: 

> To be clear, what HLS expects (and what the VTT spec defined prior to that 2016 change) is for the X-TIMESTAMP-MAP line to be among a set of non-blank lines immediately after the WEBVTT header line, followed by two or more line terminators, followed by the rest of the body.

**Comment by slifty** [comment]
Just as an update: this package *will* handle `X-TIMESTAMP-MAP`.

You need to pass `{ meta: true }` in the options:

e.g.

```
const parsedData = webvtt.parse(data, { meta: true })
```

**Comment by osk** [comment]
Yeah it's been some time since I've touched on anything here, happy to fix if the spec has changed.

Also happy to accept PR's that fix stuff :-) I can then release a new version.

**Comment by osk** [comment]
Think this is covered, otherwise feel free to open and add more info @clipod
